trigger:
- master

pool:

  name: Hosted VS2017

steps:

- task: NodeTool@0

  displayName: 'Use Node version'

  inputs:

    versionSpec: 12.x



- task: Npm@0

  displayName: 'npm install'

  inputs:

    arguments: '--force'



- task: Npm@0

  displayName: 'npm build'

  inputs:

    command: run

    arguments: 'build --force'



- task: ArchiveFiles@1

  displayName: 'Archive files '

  inputs:

    rootFolder: '$(System.DefaultWorkingDirectory)'

    includeRootFolder: false



- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: drop'