on: [push, issues]

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contribute list in readme.md
    steps:
      - name: Contribute List 
        uses: akhilmhdh/contributors-readme-action@master
        with:
          header: Developers         
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
